export const ADD_NEW_COMBINATIONS = 'ADD_NEW_COMBINATIONS';

export const REMOVE_EXISTING_COMBINATIONS = 'REMOVE_EXISTING_COMBINATIONS';

export const REPLACE_COMBINATIONS = 'REPLACE_COMBINATIONS';

export const TOGGLE_BANNER_SELECTION = 'TOGGLE_BANNER_SELECTION';
