export const UPDATE_COMBINATIONS = 'UPDATE_COMBINATIONS';

export const REMOVE_BANNER_IDS = 'REMOVE_BANNER_IDS';

export const TOGGLE_BANNER_SELECTION = 'TOGGLE_BANNER_SELECTION';

export const TOGGLE_BANNERS_VISIBILITY = 'TOGGLE_BANNERS_VISIBILITY';
